// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package spotify_mock

import (
	"github.com/emanuel3k/playlist-transfer/pkg/web"
	mock "github.com/stretchr/testify/mock"
)

// NewServiceInterfaceMock creates a new instance of ServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceInterfaceMock {
	mock := &ServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServiceInterfaceMock is an autogenerated mock type for the ServiceInterface type
type ServiceInterfaceMock struct {
	mock.Mock
}

type ServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceInterfaceMock) EXPECT() *ServiceInterfaceMock_Expecter {
	return &ServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// ExchangeCodeForToken provides a mock function for the type ServiceInterfaceMock
func (_mock *ServiceInterfaceMock) ExchangeCodeForToken(code string, state string) (string, *web.AppError) {
	ret := _mock.Called(code, state)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeCodeForToken")
	}

	var r0 string
	var r1 *web.AppError
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, *web.AppError)); ok {
		return returnFunc(code, state)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(code, state)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) *web.AppError); ok {
		r1 = returnFunc(code, state)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*web.AppError)
		}
	}
	return r0, r1
}

// ServiceInterfaceMock_ExchangeCodeForToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeCodeForToken'
type ServiceInterfaceMock_ExchangeCodeForToken_Call struct {
	*mock.Call
}

// ExchangeCodeForToken is a helper method to define mock.On call
//   - code string
//   - state string
func (_e *ServiceInterfaceMock_Expecter) ExchangeCodeForToken(code interface{}, state interface{}) *ServiceInterfaceMock_ExchangeCodeForToken_Call {
	return &ServiceInterfaceMock_ExchangeCodeForToken_Call{Call: _e.mock.On("ExchangeCodeForToken", code, state)}
}

func (_c *ServiceInterfaceMock_ExchangeCodeForToken_Call) Run(run func(code string, state string)) *ServiceInterfaceMock_ExchangeCodeForToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceInterfaceMock_ExchangeCodeForToken_Call) Return(s string, appError *web.AppError) *ServiceInterfaceMock_ExchangeCodeForToken_Call {
	_c.Call.Return(s, appError)
	return _c
}

func (_c *ServiceInterfaceMock_ExchangeCodeForToken_Call) RunAndReturn(run func(code string, state string) (string, *web.AppError)) *ServiceInterfaceMock_ExchangeCodeForToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthURI provides a mock function for the type ServiceInterfaceMock
func (_mock *ServiceInterfaceMock) GetAuthURI(userId string) string {
	ret := _mock.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthURI")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(userId)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ServiceInterfaceMock_GetAuthURI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthURI'
type ServiceInterfaceMock_GetAuthURI_Call struct {
	*mock.Call
}

// GetAuthURI is a helper method to define mock.On call
//   - userId string
func (_e *ServiceInterfaceMock_Expecter) GetAuthURI(userId interface{}) *ServiceInterfaceMock_GetAuthURI_Call {
	return &ServiceInterfaceMock_GetAuthURI_Call{Call: _e.mock.On("GetAuthURI", userId)}
}

func (_c *ServiceInterfaceMock_GetAuthURI_Call) Run(run func(userId string)) *ServiceInterfaceMock_GetAuthURI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ServiceInterfaceMock_GetAuthURI_Call) Return(s string) *ServiceInterfaceMock_GetAuthURI_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ServiceInterfaceMock_GetAuthURI_Call) RunAndReturn(run func(userId string) string) *ServiceInterfaceMock_GetAuthURI_Call {
	_c.Call.Return(run)
	return _c
}

// SetState provides a mock function for the type ServiceInterfaceMock
func (_mock *ServiceInterfaceMock) SetState(userID string, scope string) *web.AppError {
	ret := _mock.Called(userID, scope)

	if len(ret) == 0 {
		panic("no return value specified for SetState")
	}

	var r0 *web.AppError
	if returnFunc, ok := ret.Get(0).(func(string, string) *web.AppError); ok {
		r0 = returnFunc(userID, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*web.AppError)
		}
	}
	return r0
}

// ServiceInterfaceMock_SetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetState'
type ServiceInterfaceMock_SetState_Call struct {
	*mock.Call
}

// SetState is a helper method to define mock.On call
//   - userID string
//   - scope string
func (_e *ServiceInterfaceMock_Expecter) SetState(userID interface{}, scope interface{}) *ServiceInterfaceMock_SetState_Call {
	return &ServiceInterfaceMock_SetState_Call{Call: _e.mock.On("SetState", userID, scope)}
}

func (_c *ServiceInterfaceMock_SetState_Call) Run(run func(userID string, scope string)) *ServiceInterfaceMock_SetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceInterfaceMock_SetState_Call) Return(appError *web.AppError) *ServiceInterfaceMock_SetState_Call {
	_c.Call.Return(appError)
	return _c
}

func (_c *ServiceInterfaceMock_SetState_Call) RunAndReturn(run func(userID string, scope string) *web.AppError) *ServiceInterfaceMock_SetState_Call {
	_c.Call.Return(run)
	return _c
}
